import Vue from 'vue';

import {
  Avatar,
  Card,
  Button,
  Checkbox,
  Col,
  Carousel,
  DatePicker,
  Dropdown,
  Drawer,
  Descriptions,
  Empty,
  FormModel,
  Input,
  InputNumber,
  Layout,
  Menu,
  Modal,
  Pagination,
  Popconfirm,
  Popover,
  Radio,
  Row,
  Select,
  Spin,
  TimePicker,
  Table,
  Tabs,
  Tag,
  Upload,
  Icon,
  Alert,
  Anchor,
  Tooltip,
  Result,
  Divider,
  BackTop,
  Skeleton,
  ConfigProvider,
  Switch,
  Steps,
  Collapse,
  List,
  message,
  notification,
} from 'ant-design-vue';

Vue.use(List);
Vue.use(Avatar);
Vue.use(Card);
Vue.use(Button);
Vue.use(Checkbox);
Vue.use(Col);
Vue.use(Carousel);
Vue.use(DatePicker);
Vue.use(Dropdown);
Vue.use(Drawer);
Vue.use(Descriptions);
Vue.use(Empty);
Vue.use(FormModel);
Vue.use(Input);
Vue.use(Layout);
Vue.use(Menu);
Vue.use(Modal);
Vue.use(Pagination);
Vue.use(Popconfirm);
Vue.use(Popover);
Vue.use(Radio);
Vue.use(Row);
Vue.use(Select);
Vue.use(Spin);
Vue.use(TimePicker);
Vue.use(Table);
Vue.use(Tabs);
Vue.use(Tag);
Vue.use(Upload);
Vue.use(Icon);
Vue.use(Alert);
Vue.use(Anchor);
Vue.use(Tooltip);
Vue.use(Result);
Vue.use(InputNumber);
Vue.use(Divider);
Vue.use(BackTop);
Vue.use(Skeleton);
Vue.use(ConfigProvider);
Vue.use(Switch);
Vue.use(Steps);
Vue.use(Collapse);
Vue.$message = message;
Vue.prototype.$message = message;
Vue.prototype.$notification = notification;
