# logs level('log' | 'error' | 'warn' | 'debug' | 'verbose')
logger:
  - error
  - warn
  - log
  - debug

database:
  type: postgres
  host: localhost
  port: 5432
  username: postgres
  password: 123456
  database: idecs
  synchronize: true

mongoDB:
  uri: mongodb://localhost/idecs

api:
  secret: RrGPfx1sn79q

passwordReg: ^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*[\W_]).{8,20}$
