# logs level('log' | 'error' | 'warn' | 'debug' | 'verbose')
logger:
  - error
  - warn
  - log

database:
  type: postgres
  host: localhost
  port: 5432
  username: postgres
  password: 123456
  database: idecs

